// <auto-generated />
using System;
using Managment.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Management.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250330205841_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Managment.Domain.Entities.ExpenseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Title");

                    b.HasKey("Id")
                        .HasName("PK_ExpenseType_Id");

                    b.ToTable("ExpenseType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4cd034fb-ac05-4bc1-a0db-938bc254c646"),
                            CreatedAt = new DateTime(2025, 3, 30, 20, 58, 40, 656, DateTimeKind.Utc).AddTicks(5856),
                            Description = "Aquisição de ingredientes essenciais para a produção de lanches, como pães, queijos, carnes, vegetais e molhos.",
                            Title = "Compras de Ingredientes para Lanches"
                        },
                        new
                        {
                            Id = new Guid("33ff78c7-a882-4407-b702-e10b47d5a5be"),
                            CreatedAt = new DateTime(2025, 3, 30, 20, 58, 40, 656, DateTimeKind.Utc).AddTicks(6274),
                            Description = "Compra de refrigerantes, sucos, águas e outras bebidas que acompanham os lanches oferecidos aos clientes.",
                            Title = "Compras de Bebidas"
                        },
                        new
                        {
                            Id = new Guid("b5d93880-9df4-415c-9bf9-48e7a08e3bf5"),
                            CreatedAt = new DateTime(2025, 3, 30, 20, 58, 40, 656, DateTimeKind.Utc).AddTicks(6293),
                            Description = "Aquisição de doces e sobremesas, como bolos, tortas, brownies, e outros produtos de confeitaria para acompanhar o cardápio.",
                            Title = "Compras de Produtos de Confeitaria"
                        },
                        new
                        {
                            Id = new Guid("6a6333b0-d33a-449b-a992-0f5fb7877acd"),
                            CreatedAt = new DateTime(2025, 3, 30, 20, 58, 40, 656, DateTimeKind.Utc).AddTicks(6311),
                            Description = "Compra de ingredientes para preparar salgados como coxinhas, empadas, pastéis, e outros itens fritos ou assados.",
                            Title = "Compras de Ingredientes para Salgados"
                        },
                        new
                        {
                            Id = new Guid("b75b6705-2a26-49c6-9b0f-2ed5a6aba645"),
                            CreatedAt = new DateTime(2025, 3, 30, 20, 58, 40, 656, DateTimeKind.Utc).AddTicks(6331),
                            Description = "Compra de utensílios para a preparação e embalagem dos lanches, como facas, tábuas de corte, embalagens para delivery, sacolas e caixas.",
                            Title = "Compras de Utensílios e Embalagens"
                        },
                        new
                        {
                            Id = new Guid("9a4789ad-1698-485f-9263-cbbc679fca47"),
                            CreatedAt = new DateTime(2025, 3, 30, 20, 58, 40, 656, DateTimeKind.Utc).AddTicks(6349),
                            Description = "Aquisição de produtos para manter o ambiente da lanchonete limpo e higienizado, como detergentes, desinfetantes, esponjas e toalhas.",
                            Title = "Compras de Produtos de Limpeza"
                        },
                        new
                        {
                            Id = new Guid("dee49e10-8f2c-4cb6-a972-6736877da55d"),
                            CreatedAt = new DateTime(2025, 3, 30, 20, 58, 40, 656, DateTimeKind.Utc).AddTicks(6369),
                            Description = "Compra de equipamentos e utensílios necessários para a preparação dos lanches, como fogões, fritadeiras, fornos, grill, liquidificadores e outros.",
                            Title = "Compras de Equipamentos de Cozinha"
                        },
                        new
                        {
                            Id = new Guid("4b447501-4219-436b-9e5c-b170815ea12b"),
                            CreatedAt = new DateTime(2025, 3, 30, 20, 58, 40, 656, DateTimeKind.Utc).AddTicks(6387),
                            Description = "Aquisição de prateleiras, armários, geladeiras, freezers e outros itens para armazenar ingredientes e produtos de forma adequada.",
                            Title = "Compras de Itens de Armazenamento"
                        },
                        new
                        {
                            Id = new Guid("3eb07705-15a5-4136-a579-ca7022eab4d5"),
                            CreatedAt = new DateTime(2025, 3, 30, 20, 58, 40, 656, DateTimeKind.Utc).AddTicks(6406),
                            Description = "Compra de materiais de escritório, como canetas, papéis, fichários, e outros itens necessários para o funcionamento administrativo da lanchonete.",
                            Title = "Compras de Suprimentos de Escritório"
                        },
                        new
                        {
                            Id = new Guid("55546866-99c9-481a-94f8-583e11b867e2"),
                            CreatedAt = new DateTime(2025, 3, 30, 20, 58, 40, 656, DateTimeKind.Utc).AddTicks(6425),
                            Description = "Aquisição de uniformes para os funcionários, como aventais, camisetas, bonés e calçados adequados para a rotina da lanchonete.",
                            Title = "Compras de Roupas e Uniformes"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("NormalizedName");

                    b.HasKey("Id")
                        .HasName("PK_IdentityRole_Id");

                    b.HasIndex(new[] { "NormalizedName" }, "IX_IdentityRole_NormalizedName")
                        .IsUnique();

                    b.ToTable("IdentityRole", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ClaimType");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ClaimValue");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("UserId");

                    b.HasKey("Id")
                        .HasName("PK_IdentityRoleClaim_Id");

                    b.ToTable("IdentityRoleClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("BIT")
                        .HasColumnName("EmailConfirmed");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("NormalizedEmail");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("NormalizedUserName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("BIT")
                        .HasColumnName("PhoneNumberConfirmed");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("UserName");

                    b.HasKey("Id")
                        .HasName("PK_IdentityUser_Id");

                    b.HasIndex(new[] { "NormalizedUserName" }, "IX_IdentityUser_NormalizedUserName")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "IX_User_Email")
                        .IsUnique();

                    b.ToTable("IdentityUser", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ClaimType");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ClaimValue");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("UserId");

                    b.HasKey("Id")
                        .HasName("PK_IdentityUserClaim_Id");

                    b.ToTable("IdentityUserClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("LoginProvider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ProviderKey");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ProviderDisplayName");

                    b.HasKey("UserId", "LoginProvider", "ProviderKey")
                        .HasName("PK_IdentityUserLogin_UserId_LoginProvider_ProviderKey");

                    b.ToTable("IdentityUserLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("UserId");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("RoleId");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_IdentityUserRole_UserId_RoleId");

                    b.ToTable("IdentityUserRole", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("LoginProvider");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(755)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("PK_IdentityUserToken_UserId_LoginProvider_Name");

                    b.ToTable("IdentityUserToken", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
