// <auto-generated />
using System;
using Managment.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Management.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Managment.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Title");

                    b.HasKey("Id")
                        .HasName("PK_Category_Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("96caa642-c034-405c-b70c-96532723593b"),
                            CreatedAt = new DateTime(2025, 3, 28, 0, 32, 13, 216, DateTimeKind.Utc).AddTicks(7408),
                            Description = "Aquisição de ingredientes essenciais para a produção de lanches, como pães, queijos, carnes, vegetais e molhos.",
                            Title = "Compras de Ingredientes para Lanches"
                        },
                        new
                        {
                            Id = new Guid("f5d41267-7c67-4493-90d1-d319374eabd6"),
                            CreatedAt = new DateTime(2025, 3, 28, 0, 32, 13, 216, DateTimeKind.Utc).AddTicks(7784),
                            Description = "Compra de refrigerantes, sucos, águas e outras bebidas que acompanham os lanches oferecidos aos clientes.",
                            Title = "Compras de Bebidas"
                        },
                        new
                        {
                            Id = new Guid("f70a611c-5ce2-4c38-94ae-22da57826fe1"),
                            CreatedAt = new DateTime(2025, 3, 28, 0, 32, 13, 216, DateTimeKind.Utc).AddTicks(7802),
                            Description = "Aquisição de doces e sobremesas, como bolos, tortas, brownies, e outros produtos de confeitaria para acompanhar o cardápio.",
                            Title = "Compras de Produtos de Confeitaria"
                        },
                        new
                        {
                            Id = new Guid("57cfd337-a0d3-499c-b37f-93ac72dc3a72"),
                            CreatedAt = new DateTime(2025, 3, 28, 0, 32, 13, 216, DateTimeKind.Utc).AddTicks(7821),
                            Description = "Compra de ingredientes para preparar salgados como coxinhas, empadas, pastéis, e outros itens fritos ou assados.",
                            Title = "Compras de Ingredientes para Salgados"
                        },
                        new
                        {
                            Id = new Guid("f4349abd-f27a-4e11-b4b2-2b3a73a7cbf1"),
                            CreatedAt = new DateTime(2025, 3, 28, 0, 32, 13, 216, DateTimeKind.Utc).AddTicks(7840),
                            Description = "Compra de utensílios para a preparação e embalagem dos lanches, como facas, tábuas de corte, embalagens para delivery, sacolas e caixas.",
                            Title = "Compras de Utensílios e Embalagens"
                        },
                        new
                        {
                            Id = new Guid("bbf135f1-3287-418d-9400-d80be0a1ba07"),
                            CreatedAt = new DateTime(2025, 3, 28, 0, 32, 13, 216, DateTimeKind.Utc).AddTicks(7859),
                            Description = "Aquisição de produtos para manter o ambiente da lanchonete limpo e higienizado, como detergentes, desinfetantes, esponjas e toalhas.",
                            Title = "Compras de Produtos de Limpeza"
                        },
                        new
                        {
                            Id = new Guid("c57b3c4d-1b45-45aa-9d7c-2770a08d48d9"),
                            CreatedAt = new DateTime(2025, 3, 28, 0, 32, 13, 216, DateTimeKind.Utc).AddTicks(7877),
                            Description = "Compra de equipamentos e utensílios necessários para a preparação dos lanches, como fogões, fritadeiras, fornos, grill, liquidificadores e outros.",
                            Title = "Compras de Equipamentos de Cozinha"
                        },
                        new
                        {
                            Id = new Guid("86ec76ae-070f-44ea-a948-9cf758196747"),
                            CreatedAt = new DateTime(2025, 3, 28, 0, 32, 13, 216, DateTimeKind.Utc).AddTicks(7897),
                            Description = "Aquisição de prateleiras, armários, geladeiras, freezers e outros itens para armazenar ingredientes e produtos de forma adequada.",
                            Title = "Compras de Itens de Armazenamento"
                        },
                        new
                        {
                            Id = new Guid("641229e3-ec5b-4f87-9ac0-527790d42777"),
                            CreatedAt = new DateTime(2025, 3, 28, 0, 32, 13, 216, DateTimeKind.Utc).AddTicks(7916),
                            Description = "Compra de materiais de escritório, como canetas, papéis, fichários, e outros itens necessários para o funcionamento administrativo da lanchonete.",
                            Title = "Compras de Suprimentos de Escritório"
                        },
                        new
                        {
                            Id = new Guid("d9966fc2-81fa-4fff-9831-33c677d277f3"),
                            CreatedAt = new DateTime(2025, 3, 28, 0, 32, 13, 216, DateTimeKind.Utc).AddTicks(7935),
                            Description = "Aquisição de uniformes para os funcionários, como aventais, camisetas, bonés e calçados adequados para a rotina da lanchonete.",
                            Title = "Compras de Roupas e Uniformes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
